### ISSUE TITLE
feature-request: Ability to pick a date and end the poll

### ISSUE THREAD

**Issue by stevenroose** [framasoft/framadate#64] opened 2017-04-11 13:32 UTC

**Comment by tcitworld** [comment] 2018-07-06 13:23
Duplicate of https://framagit.org/framasoft/framadate/issues/208 (sorry, in french).

https://framagit.org/framasoft/framadate/merge_requests/325 will be merged in 1.2.0

**Closed by tcitworld** 2018-07-06 13:23 UTC
